//! Integration tests for the HLS transcode manager.
//!
//! These spawn real `ffmpeg` against a small video generated by ffmpeg
//! itself, so the tests need `ffmpeg` on PATH.

use std::path::PathBuf;
use std::process::Command;
use std::time::Duration;

use mythos_stream::{SessionKey, TranscodeManager, wait_for_file};
use tempfile::TempDir;
use uuid::Uuid;

fn make_test_input(dir: &std::path::Path) -> PathBuf {
    let path = dir.join("input.mp4");
    // Synthetic video + silent audio — the ABR transcoder's
    // var_stream_map references audio for each rendition, so a
    // video-only input would fail to mux.
    let status = Command::new("ffmpeg")
        .args([
            "-y",
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            "color=red:size=160x90:duration=10:rate=10",
            "-f",
            "lavfi",
            "-i",
            "anullsrc=channel_layout=stereo:sample_rate=48000",
            "-shortest",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
        ])
        .arg(&path)
        .status()
        .expect("ffmpeg available on PATH");
    assert!(status.success(), "ffmpeg failed to build test input");
    path
}

fn key() -> SessionKey {
    SessionKey {
        user_id: Uuid::now_v7(),
        movie_id: Uuid::now_v7(),
    }
}

async fn await_segment_zero(session: &mythos_stream::TranscodeSession) {
    let path = session
        .local_segment_path("480p", session.start_segment)
        .unwrap();
    // Three-rendition ABR with libx264 needs ~10–20s on slow CI; give it
    // headroom so flake isn't masquerading as a real regression.
    wait_for_file(&path, Duration::from_secs(45))
        .await
        .expect("first segment should appear within timeout");
}

#[tokio::test]
async fn ensure_session_produces_first_segment() {
    let input_dir = TempDir::new().unwrap();
    let work_dir = TempDir::new().unwrap();
    let input = make_test_input(input_dir.path());

    let manager = TranscodeManager::new(work_dir.path().to_path_buf(), mythos_stream::HwAccel::Cpu);
    let session = manager
        .ensure_session_for_segment(key(), &input, "480p", 0)
        .await
        .expect("ensure_session_for_segment");
    assert_eq!(session.start_segment, 0);
    await_segment_zero(&session).await;
}

#[tokio::test]
async fn same_segment_reuses_existing_session() {
    let input_dir = TempDir::new().unwrap();
    let work_dir = TempDir::new().unwrap();
    let input = make_test_input(input_dir.path());
    let k = key();
    let manager = TranscodeManager::new(work_dir.path().to_path_buf(), mythos_stream::HwAccel::Cpu);

    let first = manager
        .ensure_session_for_segment(k.clone(), &input, "480p", 0)
        .await
        .unwrap();
    let second = manager
        .ensure_session_for_segment(k.clone(), &input, "480p", 0)
        .await
        .unwrap();

    assert_eq!(
        std::sync::Arc::as_ptr(&first),
        std::sync::Arc::as_ptr(&second),
        "same key + same segment should reuse the session Arc"
    );
}

#[tokio::test]
async fn segment_before_session_start_forces_restart() {
    let input_dir = TempDir::new().unwrap();
    let work_dir = TempDir::new().unwrap();
    let input = make_test_input(input_dir.path());
    let k = key();
    let manager = TranscodeManager::new(work_dir.path().to_path_buf(), mythos_stream::HwAccel::Cpu);

    let first = manager
        .ensure_session_for_segment(k.clone(), &input, "480p", 1)
        .await
        .unwrap();
    let first_started = first.started_at;
    drop(first);

    // Inside the startup grace period, an incompatible request errors
    // rather than killing the in-flight session.
    match manager
        .ensure_session_for_segment(k.clone(), &input, "480p", 0)
        .await
    {
        Err(mythos_stream::TranscodeError::SessionStillBooting) => {}
        Err(other) => panic!("expected SessionStillBooting, got {other:?}"),
        Ok(_) => panic!("expected SessionStillBooting, got Ok(session)"),
    }

    // After the grace period elapses, the same incompatible request
    // does restart cleanly.
    tokio::time::sleep(std::time::Duration::from_secs(4)).await;
    let second = manager
        .ensure_session_for_segment(k, &input, "480p", 0)
        .await
        .unwrap();
    assert!(
        second.started_at > first_started,
        "earlier segment must restart the session once grace has elapsed"
    );
    assert_eq!(second.start_segment, 0);
}

#[tokio::test]
async fn local_segment_path_maps_global_index_to_session_local() {
    let input_dir = TempDir::new().unwrap();
    let work_dir = TempDir::new().unwrap();
    let input = make_test_input(input_dir.path());
    let manager = TranscodeManager::new(work_dir.path().to_path_buf(), mythos_stream::HwAccel::Cpu);

    let session = manager
        .ensure_session_for_segment(key(), &input, "480p", 3)
        .await
        .unwrap();
    // Session started at global seg 3 — global 3 is seg-0.ts on disk.
    let p0 = session.local_segment_path("480p", 3).unwrap();
    assert!(p0.ends_with("seg-0.ts"));
    let p1 = session.local_segment_path("480p", 4).unwrap();
    assert!(p1.ends_with("seg-1.ts"));
    assert!(session.local_segment_path("480p", 2).is_err());
}

#[tokio::test]
async fn stop_removes_session_and_cleans_workdir() {
    let input_dir = TempDir::new().unwrap();
    let work_dir = TempDir::new().unwrap();
    let input = make_test_input(input_dir.path());
    let k = key();
    let manager = TranscodeManager::new(work_dir.path().to_path_buf(), mythos_stream::HwAccel::Cpu);

    let session = manager
        .ensure_session_for_segment(k.clone(), &input, "480p", 0)
        .await
        .unwrap();
    let session_workdir = session.work_dir.clone();
    assert!(session_workdir.exists());
    drop(session);

    manager.stop(&k).await;

    assert!(manager.get(&k).await.is_none());
    assert!(
        !session_workdir.exists(),
        "stop() should remove the session work dir"
    );
}
